<div class="jumbotron">
    <?php
    $title = 'Edit customer';
    $this->headTitle($title);
    ?>
    <h1 class="text-center"><?= $this->escapeHtml($title); ?></h1>
    <div class="row col-lg-offset-10">
        <a class="btn btn-success" href="<?= $this->url('customer') ?>">
            Back to customers list
        </a>
    </div>
    <label>
        <span class="zdt-toolbar-color-red response-input"></span>
    </label>
    <?= $this->render('layout/form-customer'); ?>
</div>