<div class="jumbotron">
    <h1 class="text-center"><?= $this->translate('All customer calls') ?></h1>
    <div class="row col-lg-offset-10">
        <a class="btn btn-success" href="<?= $this->url('calls',array('action'=>'add', 'id' => (int)$customerId)) ?>">
            Add new call
        </a>
    </div>
    <div class="row">
        <?php foreach ($customerInfo as $info): ?>
            <p><b>Name: </b></b><?= $this->escapeHtml($info['firstName']) ?></p>
            <p><b>Last Name: </b><?= $this->escapeHtml($info['lastName']) ?></p>
            <p><b>Phone number: </b><?= $this->escapeHtml($info['phone']) ?></p>
            <p><b>Address: </b><?= $this->escapeHtml($info['address']) ?></p>
            <p><b>Status: </b><?= $this->escapeHtml($info['status']) ?></p>
            <?php if (isset($info['calls'])): ?>
                <table class="table">
                    <tr>
                        <th>Subject</th>
                        <th>Content</th>
                        <th>Edit Call</th>
                    </tr>
                    <?php foreach ($info['calls'] as $call): ?>
                        <tr>
                            <td><?= $this->escapeHtml($call['subject']) ?></td>
                            <td><?= $this->escapeHtml($call['content']) ?></td>
                            <td>
                                <a class="btn btn-warning" href="<?= $this->url('calls',array('action'=>'edit', 'id' => (int)$call['id'])) ?>">
                                    Edit Call
                                </a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </table>
            <?php  else: ?>
                <label>
                    <span class="zdt-toolbar-color-green">
                        This customer has no calls.
                    </span>
                </label>
            <?php endif ?>
        <?php endforeach ?>
    </div>
</div>