<?= $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Call '. $this->translate('center'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('plugins/jqGrid/css/ui.jqgrid.css'))
                        ->prependStylesheet($this->basePath('plugins/jqGrid/css/ui.jqgrid-bootstarp.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/script.form.js'), 'text/javascript')
            ->appendFile($this->basePath('js/script.print.js'))
            ->prependFile($this->basePath('plugins/jqGrid/js/jquery.jqGrid.min.js'))
            ->prependFile($this->basePath('plugins/jqGrid/js/i18n/grid.locale-en.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="page-wrapper">
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?= $this->url('home') ?>">
                            <img src="<?= $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>
                            &nbsp;<?= $this->translate('Skeleton Application') ?>
                        </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active">
                                <a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a>
                            </li>
                            <li class="">
                                <a href="<?= $this->url('customer') ?>"><?= $this->translate('Manage customers and their calls') ?></a>
                            </li>
                            <li class="">
                                <a href="<?= $this->url('customers-show') ?>"><?= $this->translate('Show table customers') ?></a>
                            </li>
                            <li class="">
                                <a href="<?= $this->url('newsline') ?>"><?= $this->translate('News line') ?></a>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>
            <div class="container">
                <?= $this->content; ?>
                <hr>
            </div> <!-- /container -->
            <div class="page-buffer"></div>
        </div>
        <div class="page-footer">
            <p>
                &copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. <?= $this->translate('All rights reserved.') ?>
            </p>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
